apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: mariadb
spec:
  storageClassName: managed-csi
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "app"
          operator: In
          values:
          - mariadb
