apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: wordpress
spec:
  storageClassName: managed-csi
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "app"
          operator: In
          values:
          - wordpress
